root = "/app"

[build]
  cmd = "go build -o ./tmp/hotels-service main.go"
  bin = "./tmp/hotels-service"
  include_ext = ["go", "sql"]
  
  exclude_dir = [
    "vendor",
    "tmp",
    ".git",
    "_docker/hotels-db-data",
    "logs"
  ]
  
  delay = 2000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"