root = "/app"
tmp_dir = "/app/tmp"

[build]
  cmd = "go build -o ./tmp/hotels-service main.go"
  bin = "./tmp/hotels-service"
  include_ext = ["go", "sql"]
  exclude_dir = ["vendor", "tmp"]
  delay = 2000
  stop_on_error = true

[log]
  time = true

[watch]
  dir = ["cmd", "internal", "db/migrations"]
